### ISSUE TITLE
Add text to labs to follow labels on the components

### ISSUE THREAD

**Issue by pankonen** [StateFarm-STEM/hablogger#69] opened 2023-03-10 19:00 UTC
We found some SD boards are different than the pics in lab 5
- Update ALL labs to have verbiage about following the labels on the device
- Add a tip to take a pic for reference as its hard or impossible to see once plugged in the bread board (example GPS)
- Add notes to ALWAYS triple check wiring is correct before plugging in the USB cable on all labs (we had students in a couple groups wire the SD module wrong which caused it to heat up)

**Comment by tdeknecht** [comment] 2023-10-26 01:45
This is a duplicate of issue https://github.com/StateFarm-STEM/hablogger/issues/65.

**Closed by tdeknecht** 2023-10-26 01:45 UTC
